---
 - name: Install File beat
   hosts: webservers
   become: yes
   tasks: 

   - name: Download filebeat .deb file
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb


   - name: Install filebeat
     command: dpkg -i filebeat-7.4.0-amd64.deb

   - name: Drop in filebeat.yml
     copy:
       src: /etc/ansible/files/filebeat-config.yml
       dest: /etc/filebeat/filebeat.yml

   - name: Enable and Configure system Module
     command: filebeat modules enable system


   - name: set up filebeat
     command: filebeat setup

   - name: Start filebeat Service
     command: service filebeat start


   - name: Enable service filbeat on boot
     systemd:
       name: filebeat
       enabled: yes

