---
  - name: Download Metric beat
    hosts: webservers
    become: yes
    tasks:
    - name: Download metric beat .deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Install metricbeat
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: drop in metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and configure systems module
      command: metricbeat module enable docker

    - name: metric beat set up
      command: metricbeat setup

    - name: start metricbeat service
      command: service metricbeat start

    - name: enable metricbeat service on boot
      systemd:
        name: metricbeat
        enabled: yes

